swagger: '2.0'
info:
  title: ArgentBank API
  description: API pour l'application ArgentBank
  version: '1.0.0'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/signup:
    post:
      tags:
        - User
      summary: Création d'un utilisateur
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Utilisateur créé
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Erreur de validation
  /user/login:
    post:
      tags:
        - User
      summary: Connexion utilisateur
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Login'
      responses:
        '200':
          description: Connexion réussie
          schema:
            $ref: '#/definitions/LoginResponse'
  /user/profile:
    get:
      tags:
        - User
      summary: Récupère le profil utilisateur
      security:
        - Bearer: []
      responses:
        '200':
          description: Profil utilisateur
          schema:
            $ref: '#/definitions/UserProfile'
    put:
      tags:
        - User
      summary: Met à jour le username
      security:
        - Bearer: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UpdateUsername'
      responses:
        '200':
          description: Username mis à jour
          schema:
            $ref: '#/definitions/ApiResponse'

definitions:
  User:
    type: object
    properties:
      email:
        type: string
        example: user@example.com
      password:
        type: string
        example: password123
      firstName:
        type: string
        example: John
      lastName:
        type: string
        example: Doe
      userName:
        type: string
        example: johndoe
    required:
      - email
      - password
      - firstName
      - lastName
      - userName

  Login:
    type: object
    properties:
      email:
        type: string
      password:
        type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      id:
        type: string
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      userName:
        type: string

  UpdateUsername:
    type: object
    properties:
      userName:
        type: string
    required:
      - userName

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header